Repository viky-ai/viky-ai, pull requests merged in 2019-12, with the labels that each got.

#8 [fixed] Wrong link to github/viky-ai in CONTRIBUTING.md
  CONTRIBUTING.md
Labels: documentation

#12 [fixed] Deploy env name
  .gitlab-ci.yml
Labels: deployment

#14 Fixed: Use of map-markers produces an error 500 in chatbot IU.
  webapp/app/views/chat_statements/widgets/_interactive_map.html.erb
Labels: bug

#17 [changed] Deploy : Use env name instead of env slug
  .gitlab-ci.yml
Labels: deployment

#20 Fix ownership transfert doesn't trigger NLP update
  CHANGELOG.md
  webapp/app/models/agent_transfer.rb
  webapp/test/models/agent_test.rb
Labels: bug

#19 Fix maps chabot usage in cards, lists or cards in lists regression
  CHANGELOG.md
  webapp/app/controllers/api/v1/chat_statements_controller.rb
  webapp/app/models/chat_statement.rb
  webapp/app/models/chatbot/card.rb
  webapp/app/models/chatbot/interactive_map.rb
  webapp/app/models/chatbot/list.rb
  webapp/config/locales/activerecord.en.yml
  webapp/test/controllers/api/v1/chat_statements_controller_test.rb
  webapp/test/models/chatbot/interactive_map_test.rb
Labels: bug

#21 Users management: view last created users
  CHANGELOG.md
  webapp/app/models/user.rb
  webapp/app/views/backend/users/_form_sort_by.html.erb
  webapp/app/views/backend/users/index.html.erb
  webapp/config/locales/backend.en.yml
  webapp/test/fixtures/users.yml
  webapp/test/models/user_test.rb
  webapp/test/system/backend_users_test.rb
Labels: Feature request

#25 Update SaaS to master
  .gitlab-ci.yml
  CHANGELOG.md
  webapp/.dockerignore
  webapp/Gemfile
  webapp/Gemfile.lock
  webapp/app/controllers/api/v1/chat_statements_controller.rb
  webapp/app/models/agent.rb
  webapp/app/models/agent_duplicator.rb
  webapp/app/models/agent_image_uploader.rb
  webapp/app/models/agent_transfer.rb
  webapp/app/models/chat_statement.rb
  webapp/app/models/chatbot/card.rb
  webapp/app/models/chatbot/interactive_map.rb
  webapp/app/models/chatbot/list.rb
  webapp/app/models/entities_import.rb
  webapp/app/models/entities_import_file_uploader.rb
  webapp/app/models/user.rb
  webapp/app/models/user_image_uploader.rb
  webapp/app/views/backend/users/_form_sort_by.html.erb
  webapp/app/views/backend/users/index.html.erb
  webapp/config/environments/production.rb
  webapp/config/initializers/shrine.rb
  webapp/config/locales/activerecord.en.yml
  webapp/config/locales/backend.en.yml
  webapp/db/migrate/20191204085403_migrate_to_shrine3.rb
  webapp/db/structure.sql
  webapp/docker-compose.yml
  webapp/package.json
  webapp/test/controllers/api/v1/chat_statements_controller_test.rb
  webapp/test/fixtures/users.yml
  webapp/test/models/agent_test.rb
  webapp/test/models/chatbot/interactive_map_test.rb
  webapp/test/models/user_test.rb
  webapp/test/system/backend_users_test.rb
  webapp/test/test_helper.rb
  webapp/yarn.lock
Labels: deployment

#26 Fix pull requets link in changelog
  CHANGELOG.md
Labels: bug

#28 Set pull request template as default
  .github/PULL_REQUEST_TEMPLATE.md
Labels: bug

#23 Rename formulation indicator in the platform overview
  webapp/config/locales/backend.en.yml
  webapp/test/system/backend_dashboard_test.rb
Labels: bug

#29 #21768 [changed] NLP: force language for requests
  nlp/Dockerfile
  nlp/products/bu2_nls/tests/test/nls/endpoint_interpret/test_dates.rb
  nlp/products/bu2_nls/tests/test/nls/endpoint_interpret/test_locale_score.rb
  nlp/products/bu2_nls/tests/test/nls/endpoint_interpret/test_package_numbers.rb
  nlp/products/bu2_nls/tests/test/nls/fixtures/package_with_special_char.json
  nlp/sources/ogm_nlp/lib/nlplocale.c
  nlp/sources/ogm_nlp/lib/nlprexpression.c
  nlp/sources/ogm_nlp/lib/ogm_nlp.h
Labels: Feature request

#40 Sync SaaS
  webapp/app/channels/application_cable/connection.rb
  webapp/app/javascript/app/chatbots/statements.coffee
  webapp/config/initializers/warden_hooks.rb
Labels: deployment

#42 Use logger in jobs instead of Sidekiq::Logging
  webapp/app/jobs/bot_send_start_job.rb
  webapp/app/jobs/bot_send_user_statement_job.rb
Labels: bug

#43 Sync SaaS
  webapp/app/jobs/bot_send_start_job.rb
  webapp/app/jobs/bot_send_user_statement_job.rb
Labels: deployment

#46 [fixed] CHANGELOG missing entries + review
  CHANGELOG.md
Labels: documentation

#45 #missing [change] Deploy : full deploy of dev branches become manual
  .gitlab-ci.yml
Labels: deployment

#24 Use fluent-bit to record stats asynchronously
  webapp/Dockerfile
  webapp/Gemfile
  webapp/Gemfile.lock
  webapp/app/models/interpret_request_log.rb
  webapp/app/models/interpret_request_log_client.rb
  webapp/app/models/interpret_request_reporter.rb
  webapp/app/models/statistics_visualizer.rb
  webapp/bin/docker_run.sh
  webapp/config/application.rb
  webapp/config/initializers/statistics.rb
  webapp/config/kibana/kibana-conf.json
  webapp/config/kibana/kibana-conf.ndjson
  webapp/config/statistics/fulent-bit.conf
  webapp/config/statistics/template-stats-interpret_request_log.json
  webapp/docker-compose.yml
  webapp/lib/extensions/hash_extensions.rb
  webapp/lib/tasks/statistics.rake
  webapp/test/controllers/api/v1/nlp_controller_test.rb
  webapp/test/lib/extensions/hash_extensions_test.rb
  webapp/test/models/interpret_request_log_test.rb
Labels: Feature request, deployment

#54 Remove intepreation explanation from the stats
  webapp/app/models/interpret_request_log.rb
  webapp/test/controllers/api/v1/nlp_controller_test.rb
Labels: Feature request

#55 Deploy on SaaS elastic improvement
  .gitlab-ci.yml
  CHANGELOG.md
  webapp/Dockerfile
  webapp/Gemfile
  webapp/Gemfile.lock
  webapp/app/models/interpret_request_log.rb
  webapp/app/models/interpret_request_log_client.rb
  webapp/app/models/interpret_request_reporter.rb
  webapp/app/models/statistics_visualizer.rb
  webapp/bin/docker_run.sh
  webapp/config/application.rb
  webapp/config/initializers/statistics.rb
  webapp/config/kibana/kibana-conf.json
  webapp/config/kibana/kibana-conf.ndjson
  webapp/config/statistics/fulent-bit.conf
  webapp/config/statistics/template-stats-interpret_request_log.json
  webapp/docker-compose.yml
  webapp/lib/extensions/hash_extensions.rb
  webapp/lib/tasks/statistics.rake
  webapp/test/controllers/api/v1/nlp_controller_test.rb
  webapp/test/lib/extensions/hash_extensions_test.rb
  webapp/test/models/interpret_request_log_test.rb
  webapp/yarn.lock
Labels: deployment

#52 Duplicate results when searching agent with collaborators
  webapp/app/models/agent.rb
  webapp/test/models/agent_search_test.rb
Labels: bug

#57 Retrieve current_user with cookie instead of warden env.
  CHANGELOG.md
  webapp/app/channels/application_cable/connection.rb
  webapp/app/models/user.rb
  webapp/config/routes.rb
  webapp/test/system/backend_users_test.rb
  webapp/test/test_helper.rb
Labels: bug

#61 avoid CHANGELOG.md conflict
  .gitattributes
Labels: Feature request
